# Generated by Django 5.2.4 on 2025-07-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_address',
            field=models.TextField(default='Default Address'),
            preserve_default=False,
        ),
    ]
