# Generated by Django 5.2.4 on 2025-07-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_reader_reader_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader',
            name='reader_address',
        ),
    ]
