# Generated by Django 5.2.4 on 2025-07-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_remove_reader_reader_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.CharField(max_length=255)),
                ('available_copies', models.IntegerField()),
                ('isbn', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
