# Generated by Django 5.2.4 on 2025-07-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0006_borrowtransactions_delete_borrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book', models.CharField(max_length=100)),
                ('date_borrowed', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('book', models.CharField(max_length=255)),
                ('date_borrowed', models.CharField(max_length=255)),
                ('due_date', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BorrowTransactions',
        ),
    ]
